spring:
  datasource:
    url: jdbc:mysql://localhost:10085/heycloud?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 16379
    database: 0
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true




fileoperator:
  bucket-name: upload
  storage-type: 1
  local-storage-path:
  thumb-image:
    width: 150
    height: 150
  minio-props:
    endpoint: http://localhost:9000
    bucket-name: upload
    access-key: h2u5sElxvWogL5BpbI7b
    secret-key: RvjFTEHLF7BxXrEHdB8z1XcNYJ8iWVn87Xfr4tRB


mybatis-plus:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.zhiller.heycloud.domain.model
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    banner: false

jwt:
  secret: 6L6T5LqG5L2g77yM6LWi5LqG5LiW55WM5Y+I6IO95aaC5L2V44CC
  header:
    alg: HS256
  payload:
    iss: hey-cloud-backend
    exp: 60 * 60 * 1000 * 24 * 7
    author: zhiller
