server:
  port: 20001
spring:
  application:
    name: hey-cloud-backend
  profiles:
    active: test

# swagger基本配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.zhiller.application.controller,io.zhiller.common.satoken.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 项目全局配置
cloud:
  # 异步线程池
  async:
    enable: true
    core-pool-size: 8
    max-pool-size: 40000
    queue-capacity: 80000
    thread-name-prefix: Cloud-Async-
    keep-alive-seconds: 60
    allow-core-thread-time-out: false
    wait-for-tasks-to-complete-on-shutdown: false
    await-termination-seconds: 10

